### ISSUE TITLE
A detail regarding the pack pt-br

### ISSUE THREAD

**Issue by Havokdan** [luadch/translations#2]
A detail regarding the pack pt-br, it needs to be updated since I was working last night and pack posted before I finished and finally the core translation is not loaded with when it used it, I switched pt-br to pt_br and it worked, so I suggest you correct the name in the files. Thanks for the attention and patience.

**Comment by Sopor** [comment]
I will use pt-br and we can't include those files on Transifex because some of those are already updated to the next version of Luadch. If you want you can translate cmd_usersearch.lang.pt-br and etc_userlogininfo.lang.pt-br and send them to me and i will include them in the Luadch_v2.19_pt-br_language_pack.zip (there was a few words you didn't translated).

In etc_banner.lang.pt-br and etc_motd.lang.pt-br there is a header and a footer, BANNER and MOTD. You don't want to translate those?

I noticed that you have translated `INFO DO LOGIN DO USUÁRIO` so that is why i wondering about BANNER and MOTD.

**Comment by Sopor** [comment]
@Havokdan Could you translate `Hubversion:	%s` for me so i can include it in the `etc_userlogininfo.lang.pt-br`...

**Comment by Sopor** [comment]
> I switched pt-br to pt_br and it worked,

If you use this [file](https://github.com/luadch/translations/blob/master/language_pack/pt-br/Luadch_v2.19_pt-br_language_pack.zip) it should work with `pt-br`.

**Comment by Havokdan** [comment]
> n etc_banner.lang.pt-br and etc_motd.lang.pt-br there is a header and a footer, BANNER and MOTD. You don't want to translate those?

I think it best to leave them that way.

> @Havokdan Could you translate Hubversion: %s for me so i can include it in the etc_userlogininfo.lang.pt-br...

If I have not already done so, I will now.

> If you use this file it should work with pt-br.

I used the file that was in the pack, however only the scripts appeared translated, but the core did not.

Taking advantage of the opportunity, where did you send the translations of the scripts you do not have in the transifex but is it in github?

**Comment by Havokdan** [comment]
Hubversion = Versão do hub

**Comment by Sopor** [comment]
I will send the translations from Transifex to Github, but do remember that the files from Github are not the same files as in the language packs. Those files are for the next version of Luadch. That is why we need to do this manually.
